### PR TITLE
fix: change domain

### LINKED ISSUE #8: fix invalid domain name
The Domain name needs to be valid to [assign](https://github.com/home-assistant/brands/pull/3961#pullrequestreview-1230474431)  the correct brand icon. 

https://developers.home-assistant.io/docs/creating_integration_manifest/#domain

> The domain is a short name consisting of characters and underscores.

### PR DESCRIPTION
**Pull request by CFenner**
fixes #8

### CODE REVIEW

**Comment by lkempf** [comment]
Thanks for the fix

**Comment by CFenner** [comment]
HACS installation fails for me, do we need a new release to work?

Bildschirm­foto 2022-12-28 um 01 16 35

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 214, in hacs_repository_download
    await repository.update_repository(force=True)
  File "/config/custom_components/hacs/utils/decorator.py", line 28, in wrapper
    result = await function(*args, **kwargs)
  File "/config/custom_components/hacs/repositories/integration.py", line 126, in update_repository
    if manifest := await self.async_get_integration_manifest():
  File "/config/custom_components/hacs/repositories/integration.py", line 173, in async_get_integration_manifest
    raise HacsException(f"No {RepositoryFile.MAINIFEST_JSON} file found '{manifest_path}'")
custom_components.hacs.exceptions.HacsException: No manifest.json file found 'custom_components/casambi-bt/manifest.json'
```

**Comment by lkempf** [comment]
Oh you're running into that. Hacs really doesn't like it when the folder name changes. Tell Hacs to remove the integration. This will fail but just continue the steps. Then manually remove the old folder, restart HA and now the integration should be hone. Now you can install the new version.

**Comment by CFenner** [comment]
Done, but HACS still shows the `casambi-bt` path.

Bildschirm­foto 2022-12-28 um 10 07 26

**Pull request merged**
