### PR TITLE
feat: add status entity per unit

### PR DESCRIPTION
**Pull request by CFenner**
This adds a `status` entity per ~~unit and~~ network that show the connection status `connected` or `disconnected`. 

Bildschirmfoto 2023-11-10 um 00 10 12
Bildschirmfoto 2023-11-10 um 00 12 39

### CODE REVIEW

**Comment by CFenner** [comment]
The status of this new entity but also of the existing light is not changing when I unpower my luminaire. So looks like the is an issue in the library?

**Comment by lkempf** [comment]
Can you see the changed unit state in the logs? I don't really know what online and on mean. That's just what the app calls these fields

**Comment by lkempf** [comment]
This PR is a bit to big for the couple of minutes I have right now. I'll review it as soon as possible. Thanks

**Comment by CFenner** [comment]
Will also try to split it.
Also I have an issue that the network entity should poll the status while all other unit based sensors should not.

**Comment by CFenner** [comment]
Reduced this now to just enable a status sensor for the network.

**Pull request merged**
